repos:
  - hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
    - id: commitizen
    - id: commitizen-branch
      stages:
        - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
